### ISSUE TITLE
Unexpected keys in state_dict when I run this code on cpu

### ISSUE THREAD

**Issue by JiaPei2433** [flatironinstitute/deepblast#154]
I loaded the 'deepblast-pt-18.ckpt' by runing the code on CPU as follows:
`from deepblast.dataset.utils import states2alignment
    from deepblast.utils import load_model
    align_model = load_model(
        args.deepblast_model, lm=model, tokenizer=tokenizer,
        alignment_mode=args.alignment_mode,
        device=device)`
But it showed that the error : RuntimeError: Error(s) in loading state_dict for DeepBLAST:
	Unexpected key(s) in state_dict: "aligner.lm.shared.weight",....
So there is some error when I loaded the state_dict,seemingly the keys in deepblast-pt-18.ckpt are not accordanced with the torch.

**Comment by JiaPei2433** [comment]
This error is solved when I change the deepblast file from 'deepblast-pt-l8.ckpt' to 'deepblast-v3.ckpt'. But I want to know what's difference between theses 2 '*.ckpt' file. Seemingly, 'deepblast-pt-l8.ckpt' has much more parameters, so it fits which model?

**Comment by JiaPei2433** [comment]
Hi! I'm recently seeking software and programs to search protein homology. I'm very happy that your work is so great. I've read your paper and your code. These benefit me a lot. Thank you very much!  Wish you have more good work!

**Comment by mortonjt** [comment]
Hi, the difference between the two is that `deepblast-pt-l8.ckpt` contains the entire protrans model, whereas `deepblast-v3.ckpt` only has the alignment module (hence it has a much smaller blueprint).  We had some issues making `deepblast-pt-l8.ckpt` portable across machines, which is why we introduced the new `deepblast-v3.ckpt` version.

https://github.com/flatironinstitute/deepblast/issues/139

I'm glad that the models are working for you!  Feel free to raise more issues, and I'll try to look into it.
